### ISSUE TITLE
Imprimentar loggers

### ISSUE THREAD

**Issue by megavision** [HashLoad/horse-logger#12]
Olá

Já tentei seguir seu exemplo mas até agora não foi.

parece que foi atualizado versão e não esta funcinando mais da forma como deveria

aguardo retorno

**Comment by viniciussanchez** [comment]
Boa tarde...
Poderia ser mais claro quanto ao problema e ao que se refere o "seu exemplo" por favor?
Seria a pasta samples?

**Comment by megavision** [comment]
Olá

O que fiz para resolver. Fui na master e baixei apenas o horselogger.pas e
deixei apenas ele no projeto.
Apaguei tudo que tinha sido instalado com o boss.

Agora funcionou como esta no seu video.

obrigado
*José Rubenildo da Silva*
*Analista de Sistemas*
*Celular 65 9 92392791 Whatsapp*



Em qua., 23 de mar. de 2022 às 15:26, Vinicius Sanchez <
***@***.***> escreveu:
