### ISSUE TITLE
Exception ao receber Request com Binary no Body

### ISSUE THREAD

**Issue by franklingoncalves** [HashLoad/horse-logger#13]
Ao receber uma request onde no body tem um binário o middleware gera uma exception
exception class EEncodingError with message "No mapping for the Unicode character exists in the target multi-byte code page"

Exemplo de código:

No Header da request definir  Content-Type como application/octet-stream

program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  Horse,
  Horse.OctetStream,
  Horse.Logger,
  Horse.Logger.Provider.Console,
  Horse.Logger.Provider.LogFile,
  System.SysUtils,
  System.Classes;

var
  LLogConsole: THorseLoggerConsoleConfig;
  LLogFile: THorseLoggerLogFileConfig;

begin
  LLogConsole := THorseLoggerConsoleConfig.New.SetLogFormat('${request_clientip} [${time}] ${response_status}');
  THorseLoggerManager.RegisterProvider(THorseLoggerProviderConsole.New());

  LLogFile := THorseLoggerLogFileConfig.New
    .SetLogFormat('${request_clientip} [${time}] ${response_status}');
  THorseLoggerManager.RegisterProvider(THorseLoggerProviderLogFile.New());

  THorse.Use(OctetStream);
  THorse.Use(THorseLoggerManager.HorseCallback);

  THorse.Get('/stream',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    var
      LStream: TFileStream;
    begin
      LStream := TFileStream.Create(ExtractFilePath(ParamStr(0)) + 'horse.pdf', fmOpenRead);
      Res.Send<TStream>(LStream);
    end);

  THorse.Post('/stream',
    procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
    var
      LStream: TMemoryStream;
    begin
      LStream := Req.Body<TMemoryStream>;
      LStream.SaveToFile(ExtractFilePath(ParamStr(0)) + 'horse.pdf');
      Res.Status(THTTPStatus.Created);
    end);

  THorse.Listen(9000,
    procedure(Horse: THorse)
    begin
      Writeln(Format('Server is runing on %s:%d', [Horse.Host, Horse.Port]));
      Readln;
    end);
end.

**Comment by viniciussanchez** [comment]
Obrigado por reportar....

**Comment by trainneEg7** [comment]
Ola, tambem estive com o mesmo bug, identifiquei que foi em:
 unit Horse.Logger.Manager;
na funcao DefaultHorseCallback linha 91. 
alguma coisa esta deixando o request_content_length vazio. 

nao consegui identificar em que momento esta deixando vazio, mas coloquei um try except e resolveu por hora.

**Comment by gleikocarmelo** [comment]
@franklingoncalves Poderia postar um exemplo de como esta utilizando seu middleware de Log, não estou conseguindo utiliza-lo
Desde já agradeço.

**Comment by trainneEg7** [comment]
var
 LLogFileConfig: THorseLoggerLogFileConfig;
 
begin
 HorseLoggerConfig := THorseExceptionLoggerConfig.Create('ERROR  ${exception} ;Param: ${request_query}, ${request_clientip} [${time}] ${request_user_agent} "${request_method} ${request_path_info} ${request_version}" ${response_status} ${response_content_length}', CAMINHO);

  THorse.Use(THorseExceptionLogger.New(HorseLoggerConfig));

THorse.Listen(11212,
    procedure(Horse: THorse)
    begin
      Writeln(Format('Server is runing on %d', [Horse.Port]));
      Readln;
    end);

end.

**Comment by dliocode** [comment]
Use [Horse-DataLogger](https://github.com/dliocode/horse-datalogger)

**Comment by trainneEg7** [comment]
Olá, tudo certo?


Sim, ja te envio um exemplo blz.

Danilo Lucas ***@***.***> escreveu no dia sábado, 24/12/2022
à(s) 23:22:
