### ISSUE TITLE
request_content not implemented

### ISSUE THREAD

**Issue by diegohidalgo340** [HashLoad/horse-logger#14]
request_content not implemented
I add the line:

LLog.{$IFDEF FPC}Add{$ELSE}AddPair{$ENDIF}('request_content', THorseLoggerManager.ValidateValue(AReq.RawWebRequest.Content));

in unit **Horse.Logger.Manager**

**Comment by viniciussanchez** [comment]
This feature is now available in the latest version. I just tested it and it worked.
