### ISSUE TITLE
Erro no Horse.Logger.Manager.pas(93) There is no overloaded version of 'ValidateValue' that can be called with these arguments

### ISSUE THREAD

**Issue by ramyres110** [HashLoad/horse-logger#15]
![image](https://github.com/HashLoad/horse-logger/assets/17148824/ba687197-b707-4f00-8428-9769b605ace9)

Error:
```
[dcc32 Error] Horse.Logger.Manager.pas(93): E2250 There is no overloaded version of 'ValidateValue' that can be called with these arguments
```

Problema causado no commit https://github.com/HashLoad/horse-logger/commit/ad8d6006ffdfbdac0be1cf4f6dc3ee5de64fdb2d

Há a necessidade de adicionar mais uma condicional de definição (IFDEF) para aceitar o separador!

Correção local:
```pascal
LLog.{$IFDEF FPC}Add{$ELSE}AddPair{$ENDIF}('request_content', THorseLoggerManager.ValidateValue({$IF DEFINED(FPC)} TEncoding.ANSI.GetBytes({$ENDIF}AReq.RawWebRequest.{$IF DEFINED(FPC)}Content){$ELSE}RawContent{$ENDIF}{$IF DEFINED(FPC)},''{$ENDIF}));
```

Delphi
Embarcadero® RAD Studio 10 Seattle Version 23.0.22248.579

**Comment by viniciussanchez** [comment]
Boa tarde... acho que a correção necessária não seria nem o IFDEF do FPC mas sim referente a sua versão do Delphi. Porque eu estou usando aqui o Delphi 11.2 por exemplo, e está funcionando certinho o projeto... Será que poderia nos enviar essa correção olhando para a sua versão do Delphi? Se preferir também pode nos enviar um pull request

**Comment by ramyres110** [comment]
Ocorre que no THorseLoggerManager não há um método estático ValidateValue que receba uma string e um separador!
Quando houver a diretiva do FPC vai retornar o TBytes e vai aceitar o separador e quando for Delphi (na minha versão) retorna string e não encontra o metodo!
Não enviei o PR por falta de tempo! *Porém pretendo se for pertinente!
