### ISSUE TITLE
É possivel pega a linha string gerada pelo Log ?

### ISSUE THREAD

**Issue by AlexhaifaGarcia** [HashLoad/horse-logger#18]
Olá,

Hoje o Log é criado em um arquivo que vai sendo alimentado requisição por requisição.
Porém eu gostaria de pegar a linha deste log e ao invés de gravar num arquivo, irei gravar numa tabela no meu banco de dados.
é possivel fazer isso?

Grato
Alexandre

**Comment by viniciussanchez** [comment]
Bom dia... atualmente não é possível... uma opção seria você criar o seu próprio middleware de log. Ou fazer alguma modificação que seja útil para todos e enviar um pull request para ser analisado...
