### ISSUE TITLE
Problem using the Logger

### ISSUE THREAD

**Issue by claudneysessa** [HashLoad/horse-logger#3]
Problem using the Logger

Hello, I'm using the logger but the first request it completes, after the end it hangs with the error

<html lang="en" style="font-family: sans-serif; background-color: #F5F5F5"><head>  <meta charset="utf-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Error 500: Internal Server Error</title></head><body  style="display: grid; justify-content: center; height: 100vh; vertical-align: top; margin: 0; margin-top: 20px">  <main>    <h1 style="font-size: 40px; color: #424242; text-align:center; line-height: 0.25">5🔥🙀</h1>    <p style="font-size: 24px; text-align: center; padding-left: 20px; padding-right: 20px;"><span style="color: #424242;">🐎 Internal Server Error 🐎</span><br><br><span style="color: #9e9e9e;">Access violation at address 00000000 in module 'ExemploHorseAPI.exe'. Read of address 00000000</span></p>    <p style="font-size: 18px; text-align: center; padding-left: 20px; padding-right: 20px;"><span style="color: #bdbdbd;">/pingGetByIdRestFull/1/2/teste/3</span></p>  </main></body></html>

**Comment by CarlosHe** [comment]
Can you send your sample?

**Comment by claudneysessa** [comment]
SOLVED AFTER PROJECT UPDATE/CONFIG WITH BOSS!
