### ISSUE TITLE
Support for log IP behind reverse proxy

### ISSUE THREAD

**Issue by arvanus** [HashLoad/horse-logger#4]
Hi, in the cases where Horse is running behind a reverse proxy like Apache, the default log returns the internal proxy's IP instead of the real client IP

Reading about, this info is returned as "x-forwarded-for" header info, but you must be aware of some possible faking in this info

Some sources: 
https://serverfault.com/questions/846695/preserve-client-ip-through-apache-reverse-proxy
https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address
https://en.wikipedia.org/wiki/X-Forwarded-For

What better alternative do you suggest?
Thanks!

**Comment by arvanus** [comment]
I see that Horse.RateLimit has the required method implemented:
https://github.com/dliocode/horse-ratelimit/blob/master/src/Horse.RateLimit.Utils.pas

**Comment by CarlosHe** [comment]
Hi, I will make the modification!

**Comment by CarlosHe** [comment]
The change was made
