### ISSUE TITLE
Faltando Unit

### ISSUE THREAD

**Issue by liviosa** [HashLoad/horse-logger#7]
Não consegui encontrar essa unit: Horse.Logger.Provider.LogFile

**Comment by CarlosHe** [comment]
Olá, o Logger precisa definir qual provider você quer.

Hoje você pode optar por usar dois providers ao mesmo tempo ou apenas qual quiser usar.

Você também pode criar um novo provider e ligar ao Logger.

Ao final do README, você vai encontrar os providers disponíveis.
