### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by maicorheinheimer** [HashLoad/horse-logger#8]
Bom dia, atualizei para a versão 2.0.1 e estou recebendo este memory leak abaixo,
![image](https://user-images.githubusercontent.com/65348211/109152155-7d146400-7741-11eb-8ba2-451f0dc81ae3.png)

Após executar alguma requisição ele aparece assim os memory leaks

![image](https://user-images.githubusercontent.com/65348211/109155393-df6f6380-7745-11eb-9ba3-0f3a702bfe93.png)

Estou utilizando o provider.LogFile

uses
  Horse.Logger,
  Horse.Logger.Provider.LogFile;

---

var
  LLogFileConfig: THorseLoggerLogFileConfig;

---

  LLogFileConfig := THorseLoggerLogFileConfig.New
    .SetDir(LPath);

  THorseLoggerManager.RegisterProvider(
    THorseLoggerProviderLogFile.New(LLogFileConfig)
  );

  THorse.Use(THorseLoggerManager.HorseCallback());

**Comment by CarlosHe** [comment]
Eu fiz uma correção agora! Consegue testar? Será necessário atualizar o provider também

**Comment by maicorheinheimer** [comment]
Bom dia Carlos, sim vou atualizar e testar e já dou um feedback

**Comment by maicorheinheimer** [comment]
Perfeito Carlos, resolveu os problemas dos memory leaks, atualizei e fiz o teste e esta zerado.
